#!/usr/bin/env python3
"""
Builds a single Luau file that emulates the Rojo DataModel for ModuleScripts so the pure
game-logic modules and their specs can run in the standalone `luau` CLI (no Roblox Studio).

Usage:  python3 tools/build_test_bundle.py [out_path]
Then:   luau build/test_bundle.luau

Only ModuleScripts are bundled (Scripts/LocalScripts are skipped). Modules that touch
Roblox-only APIs at require time will fail if a spec requires them; specs only require
pure modules (Config, Logic, Util, Server/Core).
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def luau_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def collect(dir_path, virtual_path, out):
    """Walk a Rojo $path directory. Returns list of (virtual_path, kind, file)."""
    init = None
    for cand in ("init.luau", "init.lua"):
        p = os.path.join(dir_path, cand)
        if os.path.isfile(p):
            init = p
    if init:
        out.append((virtual_path, "module", init))
    else:
        out.append((virtual_path, "folder", None))
    for name in sorted(os.listdir(dir_path)):
        full = os.path.join(dir_path, name)
        if os.path.isdir(full):
            collect(full, virtual_path + [name], out)
            continue
        if name in ("init.luau", "init.lua"):
            continue
        m = re.match(r"^(.*?)(\.server|\.client)?\.luau?$", name)
        if not m:
            continue
        base, suffix = m.group(1), m.group(2)
        if suffix:
            continue  # scripts are not requireable
        out.append((virtual_path + [base], "module", full))


def walk_tree(node, vpath, out):
    for key, child in node.items():
        if key.startswith("$"):
            continue
        cpath = vpath + [key]
        if "$path" in child:
            target = os.path.join(ROOT, child["$path"])
            if os.path.isdir(target):
                collect(target, cpath, out)
            elif re.match(r".*(?<!\.server)(?<!\.client)\.luau?$", target):
                out.append((cpath, "module", target))
            # single Script/LocalScript files are not requireable; skip
        else:
            out.append((cpath, "folder", None))
        walk_tree(child, cpath, out)


def transform_source(src: str) -> str:
    # `export type` is only valid at the top level; inside our wrapper function it must be plain `type`.
    src = re.sub(r"^(\s*)export\s+type\s", r"\1type ", src, flags=re.M)
    # strip --!strict etc. directives (harmless but noisy)
    src = re.sub(r"^--!\w+\s*$", "", src, flags=re.M)
    return src


PRELUDE = r'''
-- ===== Generated by tools/build_test_bundle.py. Do not edit. =====
local Node = {}
local NodeMethods = {}
Node.__index = function(self, key)
	local m = NodeMethods[key]
	if m then return m end
	local c = rawget(self, "_children")[key]
	if c then return c end
	error(("%s is not a valid member of %s"):format(tostring(key), rawget(self, "Name")), 2)
end
Node.__tostring = function(self) return rawget(self, "Name") end
local function newNode(name, className, parent)
	local n = setmetatable({ Name = name, ClassName = className, Parent = parent, _children = {} }, Node)
	if parent then rawget(parent, "_children")[name] = n end
	return n
end
function NodeMethods.WaitForChild(self, name) local c = rawget(self, "_children")[name]; if not c then error("WaitForChild timeout: " .. name) end; return c end
function NodeMethods.FindFirstChild(self, name) return rawget(self, "_children")[name] end
function NodeMethods.GetChildren(self) local t = {}; for _, c in rawget(self, "_children") do table.insert(t, c) end; table.sort(t, function(a, b) return rawget(a, "Name") < rawget(b, "Name") end); return t end
function NodeMethods.IsA(self, cls) return rawget(self, "ClassName") == cls end
function NodeMethods.GetService(self, name) return NodeMethods.WaitForChild(self, name) end
function NodeMethods.GetFullName(self) local p, parts = self, {}; while p and rawget(p, "Parent") do table.insert(parts, 1, rawget(p, "Name")); p = rawget(p, "Parent") end; return table.concat(parts, ".") end
function NodeMethods.GetAttribute() return nil end

local game = newNode("game", "DataModel", nil)
local __cache, __loading = {}, {}
local function __require(node)
	if type(node) ~= "table" then error("require expects a ModuleScript node") end
	local c = __cache[node]
	if c ~= nil then return c end
	local fn = rawget(node, "_fn")
	if not fn then error("not a ModuleScript: " .. NodeMethods.GetFullName(node)) end
	if __loading[node] then error("cyclic require: " .. NodeMethods.GetFullName(node)) end
	__loading[node] = true
	local result = fn(node)
	__loading[node] = nil
	if result == nil then error("module returned nil: " .. NodeMethods.GetFullName(node)) end
	__cache[node] = result
	return result
end

-- Minimal Roblox shims for pure modules
local Color3 = {
	fromRGB = function(r, g, b) return { R = r / 255, G = g / 255, B = b / 255 } end,
	new = function(r, g, b) return { R = r or 0, G = g or 0, B = b or 0 } end,
}
local warn = function(...) print("[warn]", ...) end
local typeof = function(v) return type(v) end
local task = {
	spawn = function(f, ...) return f(...) end,
	defer = function(f, ...) return f(...) end,
	delay = function(_, f, ...) return f(...) end,
	wait = function() return 0 end,
}
local workspace = nil
local __path = function(parts, className)
	local n = game
	for i, name in parts do
		local c = rawget(n, "_children")[name]
		if not c then c = newNode(name, (i == #parts) and className or "Folder", n) end
		n = c
	end
	return n
end
'''


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build", "test_bundle.luau")
    with open(os.path.join(ROOT, "default.project.json")) as f:
        project = json.load(f)
    entries = []
    walk_tree(project["tree"], [], entries)

    lines = [PRELUDE]
    # create all nodes first (folders + modules) so modules can reference siblings
    for vpath, kind, _ in entries:
        cls = "ModuleScript" if kind == "module" else "Folder"
        lines.append("__path({%s}, %s)" % (", ".join(luau_string(p) for p in vpath), luau_string(cls)))
    for vpath, kind, file in entries:
        if kind != "module":
            continue
        with open(file, encoding="utf-8") as fh:
            src = transform_source(fh.read())
        rel = os.path.relpath(file, ROOT)
        lines.append("do -- %s" % rel)
        lines.append("\tlocal __node = __path({%s}, \"ModuleScript\")" % ", ".join(luau_string(p) for p in vpath))
        lines.append("\trawset(__node, \"ClassName\", \"ModuleScript\")")
        lines.append("\trawset(__node, \"_fn\", function(script)")
        lines.append("\t\tlocal require = __require")
        lines.append(src)
        lines.append("\tend)")
        lines.append("end")
    lines.append(r'''
-- ===== Run all specs =====
local tests = game:GetService("ServerStorage"):WaitForChild("Tests")
local TestKit = __require(tests:WaitForChild("TestKit"))
local filter = nil
local ok = TestKit.runAll(tests, __require, filter)
if not ok then
	error("TESTS FAILED")
end
''')
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("bundle written:", out_path, "modules:", sum(1 for e in entries if e[1] == "module"))


if __name__ == "__main__":
    main()
